name: DrewAnderson.org
description: A place for me to learn
version: v1.2.0

exclude:
- "*.bash"

images_source: https://www.drewanderson.org/drewanderson.org-images
images_source_dev: http://127.0.0.1:8081
